# -*- coding: utf-8 -*-
"""movie_reccomender_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgjs_ywqqy2fhvz5_NsgfEfqCzTvNU5g

# Importing libraries
"""

import numpy as np
import pandas as pd
import ast
import pickle

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

movies.head()

credits.head()

"""# Checking the shape of dataset"""

movies = movies.merge(credits, on='title')
movies.shape

"""# Feature extraction"""

#What we will retain:
#Genres, id, keywords, title, overview, cast, crew
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]
movies.head()

movies.shape

"""# Removing he null rows"""

movies.isnull().sum()
Movies = movies.dropna(inplace=True)
movies.isnull().sum()

"""# Removing the duplicate rows (if any)"""

movies.duplicated().sum()

"""# Old genre list"""

movies.iloc[0].genres

"""# Convert string to list and cleaning"""

def convert(obj):
    L = []
    for i in ast.literal_eval(obj): # Convert string representation of list to actual list
        L.append(i['name'])
    return L

movies["genres"]=movies['genres'].apply(convert)
movies["keywords"]=movies['keywords'].apply(convert)

movies.iloc[0].genres

movies.iloc[0].keywords

movies.head()

"""# Retaining the top three cast"""

def convert3(obj):
    counter = 0
    L = []
    for i in ast.literal_eval(obj): # Convert string representation of list to actual list
        if counter!=3:
          L.append(i['name'])
          counter+=1
        else:
          break
    return L

movies['cast']=movies["cast"].apply(convert3)

movies.head()

"""# Exctracting only the director's name from crew"""

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj): # Convert string representation of list to actual list
        if i['job']=='Director':
          L.append(i['name'])
          break
    return L

movies['crew']=movies['crew'].apply(fetch_director)

movies.head()

"""# Converting the string to list (overview feature)"""

movies['overview']=movies['overview'].apply(lambda x:x.split())

movies.head()

"""# Removing the space between words and names

"""

movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
 movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
 movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
 movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head()

"""#Concatinate all the feature as tag"""

movies['tags']= movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

new_df=movies[['movie_id', 'title', 'tags']]

new_df=movies[['movie_id', 'title', 'tags']]

new_df.head()

"""# Converting the tag feature into string"""

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

"""# Converting tags to lowercase"""

new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

"""# Vectorization of tag feature
### bag of words
"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

# Convert tag to vector
cv.fit_transform(new_df['tags']).toarray()

cv.fit_transform(new_df['tags']).toarray().shape

"""# Applying stemming"""

# This is for same word recognition like (Eg- love and loved)
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

ps.stem('loved')

new_df['tags']=new_df['tags'].apply(stem)

"""# Calcuating the distance between vectors to find similarity

### Cosine distance similarity
"""

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(vectors)

"""## Recommendation logic function"""

similarity = cosine_similarity(vectors)

def recommend(movies):
  movie_index = new_df[new_df['title']==movies].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)
  return

recommend('Avatar')

pickle.dump(new_df, open('movies.pkl', 'wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))